apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-test-secondary2
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
      - 'default'
    labelSelectors:
      'app': vault-secondary2  
  stressors:
    memory:
      workers: 4
      size: 100MB
      options: [""]
    cpu:
      workers: 4
      load: 80
  duration: "10m"