apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque                             # Opaque type is used for arbitrary data
data:
  mongo-user: bW9uZ291c2Vy               # base64 encoded value of "mongouser"
  mongo-password: bW9uZ29wYXNzd29yZA==   # base64 encoded value of "mongopassword"