apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:   # define the relationship between the deployment and its pods
    matchLabels:
      app: mongo
  template:     # configuration for the pods
    metadata:
      labels:
        app: mongo
    spec:
      containers:   # configure the pods
      - name: mondodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env: # reference the secret to set the environment variables when the mongo instance starts
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:     # define the relationship between the service and its pods to forward reguests to the pods
    app: mongo  # the label of the pods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 27017